services:
  web:
    container_name: react_app
    build:
      context: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://test:test@db:5432/test
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d

volumes:
  db_data: